# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [14.x, 16.x, 18.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: echo $(ls -la)
    - name: delete last
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.NGINX_HOST }}
        username: ${{ vars.NGINX_USER }}
        key: ${{ secrets.MY_SECRET_PRIVATE }}
        script: rm -r /var/www/lakeofcolors/dist/
    - name: scp files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ vars.NGINX_HOST }}
        username: ${{ vars.NGINX_USER }}
        key: ${{ secrets.MY_SECRET_PRIVATE }}
        source: "dist/"
        target: "/var/www/belka/"

    # - run: echo $USER
    # - run: ssh ${{ vars.NGINX_USER }}@${{ vars.NGINX_HOST }} echo $(pwd)
    # - run: echo $(pwd)
    # - run: rm -rf /var/www/lakeofcolors/dist/
    # - run: mkdir -p /var/www/lakeofcolors/dist/
    # - run: cp -r $(pwd) /var/www/lakeofcolors/dist/
